# fly.toml app configuration file generated for pdr-be on 2023-07-11T23:15:37+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdr-be"
primary_region = "ams"

[http_service]
  internal_port = 4650
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
